from typing import Any
from aiosql.queries import Queries as Queries

def from_path(sql_path: str, driver_adapter: str, **kwargs: Any) -> Queries: ...
def from_str(sql: str, driver_adapter: str, **kwargs: Any) -> Queries: ...
