#!/usr/bin/env python3
"""
Generate a pyright-compatible .pyi stub for the aiosql Queries class.

Usage:
    python scripts/generate_aiosql_stubs.py

Reads all SQL files from app/queries/, inspects each query's operation type
and parameters via aiosql, then writes stubs/aiosql/queries.pyi so that
pyright can type-check calls to the Queries object.

Return type mapping:
    INSERT_RETURNING        -> Coroutine[Any, Any, dict[str, Any]]
    INSERT_UPDATE_DELETE    -> Coroutine[Any, Any, str]
    INSERT_UPDATE_DELETE_MANY -> Coroutine[Any, Any, str]
    SCRIPT                  -> Coroutine[Any, Any, str]
    SELECT                  -> AsyncIterator[dict[str, Any]]
    SELECT_ONE              -> Coroutine[Any, Any, dict[str, Any] | None]
    SELECT_VALUE            -> Coroutine[Any, Any, Any]
"""

import sys
from pathlib import Path

# Ensure project root is on path
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

import aiosql
from aiosql.types import SQLOperationType

QUERIES_DIR = ROOT / "app" / "queries"
OUT_FILE = ROOT / "stubs" / "aiosql" / "queries.pyi"

# Use dict[str, Any] instead of a driver-specific record type so that **row
# unpacking is accepted by pyright, and so the stub works with both asyncpg
# and psycopg2 (via AsyncConnectionWrapper).
RETURN_TYPE: dict[SQLOperationType, str] = {
    SQLOperationType.INSERT_RETURNING: "dict[str, Any]",
    SQLOperationType.INSERT_UPDATE_DELETE: "str",
    SQLOperationType.INSERT_UPDATE_DELETE_MANY: "str",
    SQLOperationType.SCRIPT: "str",
    SQLOperationType.SELECT: "AsyncIterator[dict[str, Any]]",
    SQLOperationType.SELECT_ONE: "dict[str, Any] | None",
    SQLOperationType.SELECT_VALUE: "Any",
}


def generate() -> None:
    queries = aiosql.from_path(str(QUERIES_DIR), "asyncpg")

    lines: list[str] = [
        "# This file is auto-generated by scripts/generate_aiosql_stubs.py",
        "# Do not edit manually — re-run the script after changing .sql files.",
        "",
        "from typing import Any",
        "from collections.abc import AsyncIterator",
        "",
        "",
        "class Queries:",
        "    # aiosql internal helpers",
        "    available_queries: list[str]",
        "",
    ]

    for name in sorted(queries.available_queries):
        fn = getattr(queries, name)
        op: SQLOperationType = fn.operation
        params: list[str] = fn.parameters

        ret = RETURN_TYPE.get(op, "Any")

        # Build keyword-only parameter list (params can be None for no-arg queries)
        param_list: list[str] = params or []
        kw_params = ", ".join(f"{p}: Any" for p in param_list)
        if kw_params:
            kw_params = f"*, {kw_params}"

        # SELECT queries are iterated with `async for` directly (not awaited),
        # so they must be declared as non-async methods returning AsyncIterator.
        # conn is typed as Any because it can be either asyncpg.Connection or
        # AsyncConnectionWrapper (psycopg2) depending on the active DB driver.
        if op == SQLOperationType.SELECT:
            sig = f"    def {name}(self, conn: Any, {kw_params}) -> AsyncIterator[dict[str, Any]]: ..."
        else:
            sig = f"    async def {name}(self, conn: Any, {kw_params}) -> {ret}: ..."
        lines.append(sig)

    lines.append("")  # trailing newline

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines))
    print(f"Written {len(queries.available_queries)} query stubs to {OUT_FILE}")


if __name__ == "__main__":
    generate()
